Repository wecode-bootcamp-korea/31-2nd-WithMe-backend, pull requests merged in 2022-04, with the labels that each got.

#1 데이터 베이스 모델링 제작
  .gitignore
  cores/__init__.py
  cores/db_uploader.py
  cores/migrations/__init__.py
  cores/models.py
  places/__init__.py
  places/admin.py
  places/apps.py
  places/migrations/0001_initial.py
  places/migrations/__init__.py
  places/models.py
  places/tests.py
  places/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  withme/settings.py
Labels: Status: 리뷰 요청

#2 [ADD]Kakao signin [Modify]Models
  .gitignore
  places/migrations/0001_initial.py
  places/migrations/0002_initial.py
  places/models.py
  users/migrations/0001_initial.py
  users/models.py
  users/views.py
Labels: Status: Accepted

#3 [Add]Signin
  users/kakao.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [modify]models 수정 부분
  places/migrations/0001_initial.py
  places/migrations/0002_initial.py
  places/models.py
  users/migrations/0001_initial.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
  withme/urls.py
Labels: Status: Accepted

#4 [modify]views.py 수정
  places/migrations/0001_initial.py
  users/kakao.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_social_id.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
  withme/settings.py
  withme/urls.py
Labels: Status: Accepted

#15 [ADD] Place information 불러오기 기능 구현
  places/tests.py
  places/urls.py
  places/views.py
  withme/urls.py
Labels: Status: Accepted

#20 위도 경도 모델추가
  places/migrations/0001_initial.py
  places/models.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#11 [ADD]ChargePoint
  cores/decorator.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#13 [ADD] Mainplacelist 구현
  places/tests.py
  places/urls.py
  places/views.py
  users/tests.py
Labels: Status: 리뷰 요청

#18 [ADD]userinfo
  users/urls.py
  users/views.py
Labels: Status: Accepted

#17 [Modify]reservation
  cores/decorator.py
  users/kakao.py
  users/tests.py
  users/urls.py
  users/views.py
  withme/settings.py
Labels: Status: Accepted

#19 [ADD] REVIEW
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#23 point 부분 컨플릭트 해결후 다시 push
  cores/decorator.py
  places/tests.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#26 [Add] 호스트 등록 기능
  users/urls.py
  users/views.py
Labels: Status: Accepted, Status: Conflict 해결 요청

#21 [ADD] Place review list 불러오는 기능 구현
  places/tests.py
  places/urls.py
  places/views.py
Labels: Status: Accepted

#27 Reservation add post method
  users/views.py
Labels: Status: Accepted

#16 [ADD] Host 정보 불러오는 기능 구현
  places/tests.py
  places/urls.py
  places/views.py
Labels: Status: Accepted

#25 Place Search 기능 구현
  places/tests.py
  places/urls.py
  places/views.py
Labels: Status: Accepted

#28 [Add] place 등록 기능
  cores/imagehandler.py
  users/tests.py
  users/urls.py
  users/views.py
  withme/settings.py
Labels: Status: Accepted

#29 [Modify] Place host information 정보 전달 기능 수정
  places/tests.py
  places/urls.py
  places/views.py
Labels: Status: Accepted

#30 [ADD] Host place list 전달 기능 구현
  places/urls.py
  places/views.py
Labels: Status: Accepted

#31 [Modify]Place information 전달 기능 수정
  places/tests.py
  places/views.py
Labels: Status: Accepted

#24 Place Reservation 기능 구현
  places/urls.py
  places/views.py
Labels: Status: Accepted

#10 [ADD] 전체 상품 필터 기능 구현
  places/tests.py
  places/urls.py
  places/views.py
Labels: Status: Accepted

#32 modify: 최종수정
  places/views.py
Labels: Status: 리뷰 요청
